### ISSUE TITLE
Non-literal type (here std::ostringstream) cannot be defined as constexpr

### ISSUE THREAD

**Issue by herve-gross** [GEOSX/cxx-utilities#107]
I am having compilation errors on Mac OSX with Xcode, Apple clang version 11.0.0 (clang-1100.0.33.8 in the following files:

src/src/ArrayView.hpp, line 284: `Variable of non-literal type 'std::ostringstream' (aka 'basic_ostringstream<char>') cannot be defined in a constexpr function`
in `GEOS_ASSERT_MSG`

Same error in:

- src/src/ArrayOfArraysView.hpp, line 198 in `GEOS_ASSERT`
- src/src/ArraySlice.hpp, line 202 in `GEOS_ASSERT_MSG`

It builds OK if I comment out the asserts.
Looks like it may be a question of [standard](https://stackoverflow.com/questions/21787488/can-have-definition-variable-of-non-literal-type-in-constexpr-function-body-c1).

**Comment by rrsettgast** [comment]
@herve-gross Does this still give you problems?

**Comment by herve-gross** [comment]
No, I do not have the issue anymore. Let me close this. Thanks for pointing it out @rrsettgast.
