### ISSUE TITLE
ArrayOfArrays segfaults after being moved from

### ISSUE THREAD

**Issue by klevzoff** [GEOSX/cxx-utilities#118]
The moved-from object will segfault on destruction with the following stack trace:
```
LvArray::ArrayOfArraysView<long long, long, false>::destroyValues<>(long, long)::{lambda(auto:1&)#1}::operator()<LvArray::ChaiBuffer<long long> >(LvArray::ChaiBuffer<long long>&) const ArrayOfArraysView.hpp:828
for_each_arg<LvArray::ArrayOfArraysView<long long, long, false>::destroyValues<>(long, long)::{lambda(auto:1&)#1}, LvArray::ChaiBuffer<long long>&>(LvArray::ArrayOfArraysView<long long, long, false>::destroyValues<>(long, long)::{lambda(auto:1&)#1}&&, LvArray::ChaiBuffer<long long>&) templateHelpers.hpp:46
LvArray::ArrayOfArraysView<long long, long, false>::destroyValues<>(long, long) ArrayOfArraysView.hpp:823
LvArray::ArrayOfArraysView<long long, long, false>::free<>() ArrayOfArraysView.hpp:536
LvArray::SparsityPattern<long long, long>::~SparsityPattern SparsityPattern.hpp:93
```

Basically, the class invariant is broken after move, because `m_numArrays` is not reset to 0 and is no longer consistent with `m_offsets` and `m_sizes` (which are empty and `destroyValues` is trying to access them). Having to reset `m_numArrays` during move to ensure safe destruction, unfortunately, will prevent us from defaulting move constructor/assignment. Maybe there's an easier way?

**Comment by corbett5** [comment]
@klevzoff I've had to git rid of the default move constructor/assignment fairly often for similar reasons. I'll fix it.

Do you have a reproducer?
